# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiProxy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_time': 'str',
        'create_user': 'str',
        'enabled': 'bool',
        'excluded': 'list[str]',
        'host': 'str',
        'id': 'int',
        'identity': 'ApiRef',
        'kind': 'str',
        'port': 'int',
        'update_user': 'str'
    }

    attribute_map = {
        'create_time': 'createTime',
        'create_user': 'createUser',
        'enabled': 'enabled',
        'excluded': 'excluded',
        'host': 'host',
        'id': 'id',
        'identity': 'identity',
        'kind': 'kind',
        'port': 'port',
        'update_user': 'updateUser'
    }

    def __init__(self, create_time=None, create_user=None, enabled=None, excluded=None, host=None, id=None, identity=None, kind=None, port=None, update_user=None, _configuration=None):  # noqa: E501
        """ApiProxy - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._create_time = None
        self._create_user = None
        self._enabled = None
        self._excluded = None
        self._host = None
        self._id = None
        self._identity = None
        self._kind = None
        self._port = None
        self._update_user = None
        self.discriminator = None

        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        if enabled is not None:
            self.enabled = enabled
        if excluded is not None:
            self.excluded = excluded
        if host is not None:
            self.host = host
        if id is not None:
            self.id = id
        if identity is not None:
            self.identity = identity
        if kind is not None:
            self.kind = kind
        if port is not None:
            self.port = port
        if update_user is not None:
            self.update_user = update_user

    @property
    def create_time(self):
        """Gets the create_time of this ApiProxy.  # noqa: E501


        :return: The create_time of this ApiProxy.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiProxy.


        :param create_time: The create_time of this ApiProxy.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiProxy.  # noqa: E501


        :return: The create_user of this ApiProxy.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiProxy.


        :param create_user: The create_user of this ApiProxy.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def enabled(self):
        """Gets the enabled of this ApiProxy.  # noqa: E501


        :return: The enabled of this ApiProxy.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ApiProxy.


        :param enabled: The enabled of this ApiProxy.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def excluded(self):
        """Gets the excluded of this ApiProxy.  # noqa: E501


        :return: The excluded of this ApiProxy.  # noqa: E501
        :rtype: list[str]
        """
        return self._excluded

    @excluded.setter
    def excluded(self, excluded):
        """Sets the excluded of this ApiProxy.


        :param excluded: The excluded of this ApiProxy.  # noqa: E501
        :type: list[str]
        """

        self._excluded = excluded

    @property
    def host(self):
        """Gets the host of this ApiProxy.  # noqa: E501


        :return: The host of this ApiProxy.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this ApiProxy.


        :param host: The host of this ApiProxy.  # noqa: E501
        :type: str
        """

        self._host = host

    @property
    def id(self):
        """Gets the id of this ApiProxy.  # noqa: E501


        :return: The id of this ApiProxy.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiProxy.


        :param id: The id of this ApiProxy.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def identity(self):
        """Gets the identity of this ApiProxy.  # noqa: E501


        :return: The identity of this ApiProxy.  # noqa: E501
        :rtype: ApiRef
        """
        return self._identity

    @identity.setter
    def identity(self, identity):
        """Sets the identity of this ApiProxy.


        :param identity: The identity of this ApiProxy.  # noqa: E501
        :type: ApiRef
        """

        self._identity = identity

    @property
    def kind(self):
        """Gets the kind of this ApiProxy.  # noqa: E501


        :return: The kind of this ApiProxy.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ApiProxy.


        :param kind: The kind of this ApiProxy.  # noqa: E501
        :type: str
        """
        allowed_values = ["http", "https"]  # noqa: E501
        if (self._configuration.client_side_validation and
                kind not in allowed_values):
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"  # noqa: E501
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def port(self):
        """Gets the port of this ApiProxy.  # noqa: E501


        :return: The port of this ApiProxy.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ApiProxy.


        :param port: The port of this ApiProxy.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def update_user(self):
        """Gets the update_user of this ApiProxy.  # noqa: E501


        :return: The update_user of this ApiProxy.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiProxy.


        :param update_user: The update_user of this ApiProxy.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiProxy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiProxy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiProxy):
            return True

        return self.to_dict() != other.to_dict()
