# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiRepository(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'branch': 'str',
        'kind': 'str',
        'path': 'str',
        'tag': 'str',
        'url': 'str'
    }

    attribute_map = {
        'branch': 'branch',
        'kind': 'kind',
        'path': 'path',
        'tag': 'tag',
        'url': 'url'
    }

    def __init__(self, branch=None, kind=None, path=None, tag=None, url=None, _configuration=None):  # noqa: E501
        """ApiRepository - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._branch = None
        self._kind = None
        self._path = None
        self._tag = None
        self._url = None
        self.discriminator = None

        if branch is not None:
            self.branch = branch
        if kind is not None:
            self.kind = kind
        if path is not None:
            self.path = path
        if tag is not None:
            self.tag = tag
        if url is not None:
            self.url = url

    @property
    def branch(self):
        """Gets the branch of this ApiRepository.  # noqa: E501


        :return: The branch of this ApiRepository.  # noqa: E501
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this ApiRepository.


        :param branch: The branch of this ApiRepository.  # noqa: E501
        :type: str
        """

        self._branch = branch

    @property
    def kind(self):
        """Gets the kind of this ApiRepository.  # noqa: E501


        :return: The kind of this ApiRepository.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ApiRepository.


        :param kind: The kind of this ApiRepository.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def path(self):
        """Gets the path of this ApiRepository.  # noqa: E501


        :return: The path of this ApiRepository.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ApiRepository.


        :param path: The path of this ApiRepository.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def tag(self):
        """Gets the tag of this ApiRepository.  # noqa: E501


        :return: The tag of this ApiRepository.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ApiRepository.


        :param tag: The tag of this ApiRepository.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def url(self):
        """Gets the url of this ApiRepository.  # noqa: E501


        :return: The url of this ApiRepository.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ApiRepository.


        :param url: The url of this ApiRepository.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiRepository, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiRepository):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiRepository):
            return True

        return self.to_dict() != other.to_dict()
