# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiTagType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'colour': 'str',
        'create_time': 'str',
        'create_user': 'str',
        'id': 'int',
        'name': 'str',
        'rank': 'int',
        'tags': 'list[ApiRef]',
        'update_user': 'str',
        'username': 'str'
    }

    attribute_map = {
        'colour': 'colour',
        'create_time': 'createTime',
        'create_user': 'createUser',
        'id': 'id',
        'name': 'name',
        'rank': 'rank',
        'tags': 'tags',
        'update_user': 'updateUser',
        'username': 'username'
    }

    def __init__(self, colour=None, create_time=None, create_user=None, id=None, name=None, rank=None, tags=None, update_user=None, username=None, _configuration=None):  # noqa: E501
        """ApiTagType - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._colour = None
        self._create_time = None
        self._create_user = None
        self._id = None
        self._name = None
        self._rank = None
        self._tags = None
        self._update_user = None
        self._username = None
        self.discriminator = None

        if colour is not None:
            self.colour = colour
        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        if id is not None:
            self.id = id
        self.name = name
        if rank is not None:
            self.rank = rank
        if tags is not None:
            self.tags = tags
        if update_user is not None:
            self.update_user = update_user
        if username is not None:
            self.username = username

    @property
    def colour(self):
        """Gets the colour of this ApiTagType.  # noqa: E501


        :return: The colour of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._colour

    @colour.setter
    def colour(self, colour):
        """Sets the colour of this ApiTagType.


        :param colour: The colour of this ApiTagType.  # noqa: E501
        :type: str
        """

        self._colour = colour

    @property
    def create_time(self):
        """Gets the create_time of this ApiTagType.  # noqa: E501


        :return: The create_time of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiTagType.


        :param create_time: The create_time of this ApiTagType.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiTagType.  # noqa: E501


        :return: The create_user of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiTagType.


        :param create_user: The create_user of this ApiTagType.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def id(self):
        """Gets the id of this ApiTagType.  # noqa: E501


        :return: The id of this ApiTagType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiTagType.


        :param id: The id of this ApiTagType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApiTagType.  # noqa: E501


        :return: The name of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiTagType.


        :param name: The name of this ApiTagType.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def rank(self):
        """Gets the rank of this ApiTagType.  # noqa: E501


        :return: The rank of this ApiTagType.  # noqa: E501
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this ApiTagType.


        :param rank: The rank of this ApiTagType.  # noqa: E501
        :type: int
        """

        self._rank = rank

    @property
    def tags(self):
        """Gets the tags of this ApiTagType.  # noqa: E501


        :return: The tags of this ApiTagType.  # noqa: E501
        :rtype: list[ApiRef]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ApiTagType.


        :param tags: The tags of this ApiTagType.  # noqa: E501
        :type: list[ApiRef]
        """

        self._tags = tags

    @property
    def update_user(self):
        """Gets the update_user of this ApiTagType.  # noqa: E501


        :return: The update_user of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiTagType.


        :param update_user: The update_user of this ApiTagType.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    @property
    def username(self):
        """Gets the username of this ApiTagType.  # noqa: E501


        :return: The username of this ApiTagType.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ApiTagType.


        :param username: The username of this ApiTagType.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiTagType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiTagType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiTagType):
            return True

        return self.to_dict() != other.to_dict()
