# coding: utf-8

"""
    tackle2.0 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiReview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application': 'ApiRef',
        'business_criticality': 'int',
        'comments': 'str',
        'create_time': 'str',
        'create_user': 'str',
        'effort_estimate': 'str',
        'id': 'int',
        'proposed_action': 'str',
        'update_user': 'str',
        'work_priority': 'int'
    }

    attribute_map = {
        'application': 'application',
        'business_criticality': 'businessCriticality',
        'comments': 'comments',
        'create_time': 'createTime',
        'create_user': 'createUser',
        'effort_estimate': 'effortEstimate',
        'id': 'id',
        'proposed_action': 'proposedAction',
        'update_user': 'updateUser',
        'work_priority': 'workPriority'
    }

    def __init__(self, application=None, business_criticality=None, comments=None, create_time=None, create_user=None, effort_estimate=None, id=None, proposed_action=None, update_user=None, work_priority=None, _configuration=None):  # noqa: E501
        """ApiReview - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._application = None
        self._business_criticality = None
        self._comments = None
        self._create_time = None
        self._create_user = None
        self._effort_estimate = None
        self._id = None
        self._proposed_action = None
        self._update_user = None
        self._work_priority = None
        self.discriminator = None

        self.application = application
        if business_criticality is not None:
            self.business_criticality = business_criticality
        if comments is not None:
            self.comments = comments
        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        if effort_estimate is not None:
            self.effort_estimate = effort_estimate
        if id is not None:
            self.id = id
        if proposed_action is not None:
            self.proposed_action = proposed_action
        if update_user is not None:
            self.update_user = update_user
        if work_priority is not None:
            self.work_priority = work_priority

    @property
    def application(self):
        """Gets the application of this ApiReview.  # noqa: E501


        :return: The application of this ApiReview.  # noqa: E501
        :rtype: ApiRef
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ApiReview.


        :param application: The application of this ApiReview.  # noqa: E501
        :type: ApiRef
        """
        if self._configuration.client_side_validation and application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")  # noqa: E501

        self._application = application

    @property
    def business_criticality(self):
        """Gets the business_criticality of this ApiReview.  # noqa: E501


        :return: The business_criticality of this ApiReview.  # noqa: E501
        :rtype: int
        """
        return self._business_criticality

    @business_criticality.setter
    def business_criticality(self, business_criticality):
        """Sets the business_criticality of this ApiReview.


        :param business_criticality: The business_criticality of this ApiReview.  # noqa: E501
        :type: int
        """

        self._business_criticality = business_criticality

    @property
    def comments(self):
        """Gets the comments of this ApiReview.  # noqa: E501


        :return: The comments of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this ApiReview.


        :param comments: The comments of this ApiReview.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def create_time(self):
        """Gets the create_time of this ApiReview.  # noqa: E501


        :return: The create_time of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiReview.


        :param create_time: The create_time of this ApiReview.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiReview.  # noqa: E501


        :return: The create_user of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiReview.


        :param create_user: The create_user of this ApiReview.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def effort_estimate(self):
        """Gets the effort_estimate of this ApiReview.  # noqa: E501


        :return: The effort_estimate of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._effort_estimate

    @effort_estimate.setter
    def effort_estimate(self, effort_estimate):
        """Sets the effort_estimate of this ApiReview.


        :param effort_estimate: The effort_estimate of this ApiReview.  # noqa: E501
        :type: str
        """

        self._effort_estimate = effort_estimate

    @property
    def id(self):
        """Gets the id of this ApiReview.  # noqa: E501


        :return: The id of this ApiReview.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiReview.


        :param id: The id of this ApiReview.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def proposed_action(self):
        """Gets the proposed_action of this ApiReview.  # noqa: E501


        :return: The proposed_action of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._proposed_action

    @proposed_action.setter
    def proposed_action(self, proposed_action):
        """Sets the proposed_action of this ApiReview.


        :param proposed_action: The proposed_action of this ApiReview.  # noqa: E501
        :type: str
        """

        self._proposed_action = proposed_action

    @property
    def update_user(self):
        """Gets the update_user of this ApiReview.  # noqa: E501


        :return: The update_user of this ApiReview.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiReview.


        :param update_user: The update_user of this ApiReview.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    @property
    def work_priority(self):
        """Gets the work_priority of this ApiReview.  # noqa: E501


        :return: The work_priority of this ApiReview.  # noqa: E501
        :rtype: int
        """
        return self._work_priority

    @work_priority.setter
    def work_priority(self, work_priority):
        """Sets the work_priority of this ApiReview.


        :param work_priority: The work_priority of this ApiReview.  # noqa: E501
        :type: int
        """

        self._work_priority = work_priority

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiReview, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiReview):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiReview):
            return True

        return self.to_dict() != other.to_dict()
