# coding: utf-8

"""
    tackle2.0 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ApiTaskGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'addon': 'str',
        'bucket': 'str',
        'create_time': 'str',
        'create_user': 'str',
        'data': 'object',
        'id': 'int',
        'name': 'str',
        'purged': 'bool',
        'state': 'str',
        'tasks': 'list[ApiTask]',
        'update_user': 'str'
    }

    attribute_map = {
        'addon': 'addon',
        'bucket': 'bucket',
        'create_time': 'createTime',
        'create_user': 'createUser',
        'data': 'data',
        'id': 'id',
        'name': 'name',
        'purged': 'purged',
        'state': 'state',
        'tasks': 'tasks',
        'update_user': 'updateUser'
    }

    def __init__(self, addon=None, bucket=None, create_time=None, create_user=None, data=None, id=None, name=None, purged=None, state=None, tasks=None, update_user=None, _configuration=None):  # noqa: E501
        """ApiTaskGroup - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._addon = None
        self._bucket = None
        self._create_time = None
        self._create_user = None
        self._data = None
        self._id = None
        self._name = None
        self._purged = None
        self._state = None
        self._tasks = None
        self._update_user = None
        self.discriminator = None

        if addon is not None:
            self.addon = addon
        if bucket is not None:
            self.bucket = bucket
        if create_time is not None:
            self.create_time = create_time
        if create_user is not None:
            self.create_user = create_user
        self.data = data
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if purged is not None:
            self.purged = purged
        if state is not None:
            self.state = state
        if tasks is not None:
            self.tasks = tasks
        if update_user is not None:
            self.update_user = update_user

    @property
    def addon(self):
        """Gets the addon of this ApiTaskGroup.  # noqa: E501


        :return: The addon of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._addon

    @addon.setter
    def addon(self, addon):
        """Sets the addon of this ApiTaskGroup.


        :param addon: The addon of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._addon = addon

    @property
    def bucket(self):
        """Gets the bucket of this ApiTaskGroup.  # noqa: E501


        :return: The bucket of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this ApiTaskGroup.


        :param bucket: The bucket of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._bucket = bucket

    @property
    def create_time(self):
        """Gets the create_time of this ApiTaskGroup.  # noqa: E501


        :return: The create_time of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiTaskGroup.


        :param create_time: The create_time of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def create_user(self):
        """Gets the create_user of this ApiTaskGroup.  # noqa: E501


        :return: The create_user of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this ApiTaskGroup.


        :param create_user: The create_user of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def data(self):
        """Gets the data of this ApiTaskGroup.  # noqa: E501


        :return: The data of this ApiTaskGroup.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ApiTaskGroup.


        :param data: The data of this ApiTaskGroup.  # noqa: E501
        :type: object
        """
        if self._configuration.client_side_validation and data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def id(self):
        """Gets the id of this ApiTaskGroup.  # noqa: E501


        :return: The id of this ApiTaskGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiTaskGroup.


        :param id: The id of this ApiTaskGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApiTaskGroup.  # noqa: E501


        :return: The name of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiTaskGroup.


        :param name: The name of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def purged(self):
        """Gets the purged of this ApiTaskGroup.  # noqa: E501


        :return: The purged of this ApiTaskGroup.  # noqa: E501
        :rtype: bool
        """
        return self._purged

    @purged.setter
    def purged(self, purged):
        """Sets the purged of this ApiTaskGroup.


        :param purged: The purged of this ApiTaskGroup.  # noqa: E501
        :type: bool
        """

        self._purged = purged

    @property
    def state(self):
        """Gets the state of this ApiTaskGroup.  # noqa: E501


        :return: The state of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ApiTaskGroup.


        :param state: The state of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def tasks(self):
        """Gets the tasks of this ApiTaskGroup.  # noqa: E501


        :return: The tasks of this ApiTaskGroup.  # noqa: E501
        :rtype: list[ApiTask]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """Sets the tasks of this ApiTaskGroup.


        :param tasks: The tasks of this ApiTaskGroup.  # noqa: E501
        :type: list[ApiTask]
        """

        self._tasks = tasks

    @property
    def update_user(self):
        """Gets the update_user of this ApiTaskGroup.  # noqa: E501


        :return: The update_user of this ApiTaskGroup.  # noqa: E501
        :rtype: str
        """
        return self._update_user

    @update_user.setter
    def update_user(self, update_user):
        """Sets the update_user of this ApiTaskGroup.


        :param update_user: The update_user of this ApiTaskGroup.  # noqa: E501
        :type: str
        """

        self._update_user = update_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiTaskGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiTaskGroup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiTaskGroup):
            return True

        return self.to_dict() != other.to_dict()
