# coding: utf-8

"""
    tackle2.0 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.setting_api import SettingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingApi(unittest.TestCase):
    """SettingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.setting_api.SettingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settings_get(self):
        """Test case for settings_get

        List all settings.  # noqa: E501
        """
        pass

    def test_settings_key_delete(self):
        """Test case for settings_key_delete

        Delete a setting.  # noqa: E501
        """
        pass

    def test_settings_key_get(self):
        """Test case for settings_key_get

        Get a setting by its key.  # noqa: E501
        """
        pass

    def test_settings_key_put(self):
        """Test case for settings_key_put

        Update a setting.  # noqa: E501
        """
        pass

    def test_settings_post(self):
        """Test case for settings_post

        Create a setting.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
