# coding: utf-8

"""
    tackle2.0 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_import_summary import ApiImportSummary  # noqa: E501
from swagger_client.rest import ApiException


class TestApiImportSummary(unittest.TestCase):
    """ApiImportSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiImportSummary(self):
        """Test ApiImportSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_import_summary.ApiImportSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
