# coding: utf-8

"""
    tackle2.0 api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_business_service import ApiBusinessService  # noqa: E501
from swagger_client.rest import ApiException


class TestApiBusinessService(unittest.TestCase):
    """ApiBusinessService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiBusinessService(self):
        """Test ApiBusinessService"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_business_service.ApiBusinessService()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
