# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.get_api import GetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetApi(unittest.TestCase):
    """GetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.get_api.GetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addons_get(self):
        """Test case for addons_get

        List all addons.  # noqa: E501
        """
        pass

    def test_addons_name_get(self):
        """Test case for addons_name_get

        Get an addon by name.  # noqa: E501
        """
        pass

    def test_application_inventory_application_id_identities_get(self):
        """Test case for application_inventory_application_id_identities_get

        List identities for an application.  # noqa: E501
        """
        pass

    def test_application_inventory_application_import_id_get(self):
        """Test case for application_inventory_application_import_id_get

        Get an import by ID.  # noqa: E501
        """
        pass

    def test_application_inventory_import_summary_id_get(self):
        """Test case for application_inventory_import_summary_id_get

        Get an import summary by ID.  # noqa: E501
        """
        pass

    def test_applications_id_get(self):
        """Test case for applications_id_get

        Get an application by ID.  # noqa: E501
        """
        pass

    def test_applications_id_tasks_id_content_wildcard_get(self):
        """Test case for applications_id_tasks_id_content_wildcard_get

        Get bucket content by ID and path.  # noqa: E501
        """
        pass

    def test_bucket_id_content_wildcard_post(self):
        """Test case for bucket_id_content_wildcard_post

        Upload bucket content by task ID and path.  # noqa: E501
        """
        pass

    def test_businessservices_id_get(self):
        """Test case for businessservices_id_get

        Get a business service by ID.  # noqa: E501
        """
        pass

    def test_dependencies_id_get(self):
        """Test case for dependencies_id_get

        Get a dependency by ID.  # noqa: E501
        """
        pass

    def test_identities_get(self):
        """Test case for identities_get

        List all identities.  # noqa: E501
        """
        pass

    def test_identities_id_get(self):
        """Test case for identities_id_get

        Get an identity by ID.  # noqa: E501
        """
        pass

    def test_jobfunctions_get(self):
        """Test case for jobfunctions_get

        List all job functions.  # noqa: E501
        """
        pass

    def test_jobfunctions_id_get(self):
        """Test case for jobfunctions_id_get

        Get a job function by ID.  # noqa: E501
        """
        pass

    def test_proxies_get(self):
        """Test case for proxies_get

        List all proxies.  # noqa: E501
        """
        pass

    def test_proxies_id_get(self):
        """Test case for proxies_id_get

        Get an proxy by ID.  # noqa: E501
        """
        pass

    def test_reviews_get(self):
        """Test case for reviews_get

        List all reviews.  # noqa: E501
        """
        pass

    def test_reviews_id_get(self):
        """Test case for reviews_id_get

        Get a review by ID.  # noqa: E501
        """
        pass

    def test_settings_key_get(self):
        """Test case for settings_key_get

        Get a setting by its key.  # noqa: E501
        """
        pass

    def test_stakeholdergroups_get(self):
        """Test case for stakeholdergroups_get

        List all stakeholder groups.  # noqa: E501
        """
        pass

    def test_stakeholdergroups_id_get(self):
        """Test case for stakeholdergroups_id_get

        Get a stakeholder group by ID.  # noqa: E501
        """
        pass

    def test_stakeholders_get(self):
        """Test case for stakeholders_get

        List all stakeholders.  # noqa: E501
        """
        pass

    def test_stakeholders_id_get(self):
        """Test case for stakeholders_id_get

        Get a stakeholder by ID.  # noqa: E501
        """
        pass

    def test_tags_get(self):
        """Test case for tags_get

        List all tags.  # noqa: E501
        """
        pass

    def test_tags_id_get(self):
        """Test case for tags_id_get

        Get a tag by ID.  # noqa: E501
        """
        pass

    def test_tagtypes_get(self):
        """Test case for tagtypes_get

        List all tag types.  # noqa: E501
        """
        pass

    def test_tagtypes_id_get(self):
        """Test case for tagtypes_id_get

        Get a tag type by ID.  # noqa: E501
        """
        pass

    def test_taskgroups_get(self):
        """Test case for taskgroups_get

        List all task groups.  # noqa: E501
        """
        pass

    def test_taskgroups_id_bucket_wildcard_get(self):
        """Test case for taskgroups_id_bucket_wildcard_get

        Get bucket content by ID and path.  # noqa: E501
        """
        pass

    def test_taskgroups_id_get(self):
        """Test case for taskgroups_id_get

        Get a task group by ID.  # noqa: E501
        """
        pass

    def test_tasks_get(self):
        """Test case for tasks_get

        List all tasks.  # noqa: E501
        """
        pass

    def test_tasks_id_bucket_wildcard_get(self):
        """Test case for tasks_id_bucket_wildcard_get

        Get bucket content by ID and path.  # noqa: E501
        """
        pass

    def test_tasks_id_bucket_wildcard_post(self):
        """Test case for tasks_id_bucket_wildcard_post

        Upload bucket content by task ID and path.  # noqa: E501
        """
        pass

    def test_tasks_id_get(self):
        """Test case for tasks_id_get

        Get a task by ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
