# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delete_api import DeleteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteApi(unittest.TestCase):
    """DeleteApi unit test stubs"""

    def setUp(self):
        configuration = swagger_client.Configuration()
        configuration.host = "12"
        self.api = swagger_client.api.delete_api.DeleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_application_inventory_application_import_id_delete(self):
        """Test case for application_inventory_application_import_id_delete

        Delete an import.  # noqa: E501
        """
        pass

    def test_application_inventory_import_summary_id_delete(self):
        """Test case for application_inventory_import_summary_id_delete

        Delete an import summary and associated import records.  # noqa: E501
        """
        pass

    def test_applications_id_delete(self):
        """Test case for applications_id_delete

        Delete an application.  # noqa: E501
        """
        pass

    def test_businessservices_id_delete(self):
        """Test case for businessservices_id_delete

        Delete a business service.  # noqa: E501
        """
        pass

    def test_dependencies_id_delete(self):
        """Test case for dependencies_id_delete

        Delete a dependency.  # noqa: E501
        """
        pass

    def test_identities_id_delete(self):
        """Test case for identities_id_delete

        Delete an identity.  # noqa: E501
        """
        pass

    def test_jobfunctions_id_delete(self):
        """Test case for jobfunctions_id_delete

        Delete a job function.  # noqa: E501
        """
        pass

    def test_proxies_id_delete(self):
        """Test case for proxies_id_delete

        Delete an proxy.  # noqa: E501
        """
        pass

    def test_reviews_id_delete(self):
        """Test case for reviews_id_delete

        Delete a review.  # noqa: E501
        """
        pass

    def test_settings_key_delete(self):
        """Test case for settings_key_delete

        Delete a setting.  # noqa: E501
        """
        pass

    def test_stakeholdergroups_id_delete(self):
        """Test case for stakeholdergroups_id_delete

        Delete a stakeholder group.  # noqa: E501
        """
        pass

    def test_stakeholders_id_delete(self):
        """Test case for stakeholders_id_delete

        Delete a stakeholder.  # noqa: E501
        """
        pass

    def test_tags_id_delete(self):
        """Test case for tags_id_delete

        Delete a tag.  # noqa: E501
        """
        pass

    def test_tagtypes_id_delete(self):
        """Test case for tagtypes_id_delete

        Delete a tag type.  # noqa: E501
        """
        pass

    def test_taskgroups_id_delete(self):
        """Test case for taskgroups_id_delete

        Delete a task group.  # noqa: E501
        """
        pass

    def test_tasks_id_delete(self):
        """Test case for tasks_id_delete

        Delete a task.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
