# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_job_function import ApiJobFunction  # noqa: E501
from swagger_client.rest import ApiException


class TestApiJobFunction(unittest.TestCase):
    """ApiJobFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiJobFunction(self):
        """Test ApiJobFunction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_job_function.ApiJobFunction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
