# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.post_api import PostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPostApi(unittest.TestCase):
    """PostApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.post_api.PostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_application_inventory_file_upload_post(self):
        """Test case for application_inventory_file_upload_post

        Upload a CSV containing applications and dependencies to import.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
