# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.create_api import CreateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateApi(unittest.TestCase):
    """CreateApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.create_api.CreateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applications_post(self):
        """Test case for applications_post

        Create an application.  # noqa: E501
        """
        pass

    def test_businessservices_post(self):
        """Test case for businessservices_post

        Create a business service.  # noqa: E501
        """
        pass

    def test_dependencies_post(self):
        """Test case for dependencies_post

        Create a dependency.  # noqa: E501
        """
        pass

    def test_identities_post(self):
        """Test case for identities_post

        Create an identity.  # noqa: E501
        """
        pass

    def test_jobfunctions_post(self):
        """Test case for jobfunctions_post

        Create a job function.  # noqa: E501
        """
        pass

    def test_proxies_post(self):
        """Test case for proxies_post

        Create an proxy.  # noqa: E501
        """
        pass

    def test_reviews_post(self):
        """Test case for reviews_post

        Create a review.  # noqa: E501
        """
        pass

    def test_settings_post(self):
        """Test case for settings_post

        Create a setting.  # noqa: E501
        """
        pass

    def test_stakeholdergroups_post(self):
        """Test case for stakeholdergroups_post

        Create a stakeholder group.  # noqa: E501
        """
        pass

    def test_stakeholders_post(self):
        """Test case for stakeholders_post

        Create a stakeholder.  # noqa: E501
        """
        pass

    def test_tags_post(self):
        """Test case for tags_post

        Create a tag.  # noqa: E501
        """
        pass

    def test_tagtypes_post(self):
        """Test case for tagtypes_post

        Create a tag type.  # noqa: E501
        """
        pass

    def test_taskgroups_post(self):
        """Test case for taskgroups_post

        Create a task group.  # noqa: E501
        """
        pass

    def test_tasks_post(self):
        """Test case for tasks_post

        Create a task.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
