# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.update_api import UpdateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateApi(unittest.TestCase):
    """UpdateApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.update_api.UpdateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applications_id_put(self):
        """Test case for applications_id_put

        Update an application.  # noqa: E501
        """
        pass

    def test_businessservices_id_put(self):
        """Test case for businessservices_id_put

        Update a business service.  # noqa: E501
        """
        pass

    def test_identities_id_put(self):
        """Test case for identities_id_put

        Update an identity.  # noqa: E501
        """
        pass

    def test_jobfunctions_id_put(self):
        """Test case for jobfunctions_id_put

        Update a job function.  # noqa: E501
        """
        pass

    def test_proxies_id_put(self):
        """Test case for proxies_id_put

        Update an proxy.  # noqa: E501
        """
        pass

    def test_reviews_id_put(self):
        """Test case for reviews_id_put

        Update a review.  # noqa: E501
        """
        pass

    def test_settings_key_put(self):
        """Test case for settings_key_put

        Update a setting.  # noqa: E501
        """
        pass

    def test_stakeholdergroups_id_put(self):
        """Test case for stakeholdergroups_id_put

        Update a stakeholder group.  # noqa: E501
        """
        pass

    def test_stakeholders_id_put(self):
        """Test case for stakeholders_id_put

        Update a stakeholder.  # noqa: E501
        """
        pass

    def test_tags_id_put(self):
        """Test case for tags_id_put

        Update a tag.  # noqa: E501
        """
        pass

    def test_tagtypes_id_put(self):
        """Test case for tagtypes_id_put

        Update a tag type.  # noqa: E501
        """
        pass

    def test_taskgroups_id_submit_put(self):
        """Test case for taskgroups_id_submit_put

        Submit a task group.  # noqa: E501
        """
        pass

    def test_tasks_id_put(self):
        """Test case for tasks_id_put

        Update a task group.  # noqa: E501
        """
        pass

    def test_tasks_id_report_delete(self):
        """Test case for tasks_id_report_delete

        Delete a task report.  # noqa: E501
        """
        pass

    def test_tasks_id_report_post(self):
        """Test case for tasks_id_report_post

        Create a task report.  # noqa: E501
        """
        pass

    def test_tasks_id_report_put(self):
        """Test case for tasks_id_report_put

        Update a task report.  # noqa: E501
        """
        pass

    def test_tasks_id_submit_put(self):
        """Test case for tasks_id_submit_put

        Submit a task.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
